### ISSUE TITLE
Enable FaceID in Settings -> Privacy

### ISSUE THREAD

**Issue by chrisswanda** [olvid-io/olvid-ios#1]
Under screen lock, the only option is to login with passcode.  Are there plans in the future to enable FaceID for authentication?

**Comment by tbaigner** [comment]
Hello 👋. Olvid does allow login with FaceID. Could you please open the Settings app, tap on Olvid, and make sure Olvid is allowed to use FaceID? Please let us know if this works for you.

**Comment by chrisswanda** [comment]
Interesting.  FaceID was unselected in Settings for some reason.  When unselected, the app shows no option for using FaceID. 
![IMG_4165](https://user-images.githubusercontent.com/45573533/148929137-8424baf4-2bb2-40ed-8799-56abae819461.PNG)
 
I enabled it and it is now working.  Thanks for following up.
