### ISSUE TITLE
La restauration a échoué [Android -> iOS]

### ISSUE THREAD

**Issue by dleurs** [olvid-io/olvid-ios#2]
Bonjour,

Mon téléphone Android a pris l'eau, il ne fonctionne plus

J'avais réalisé une sauvegarde fichier.

Sur mon nouvel iPhone, lorsque j'essaye de réalisé la restauration, j'ai le message "La restauration a échoué La sauvegarde n'a malheureusement pas pu être restaurée"

![336981358_1349091889218830_7694688493613710155_n](https://user-images.githubusercontent.com/58068925/229826536-adcf3e51-408d-44ac-b2be-e0510f458859.jpg)

C'est embêtant !

Bonne journée

**Comment by tbaigner** [comment]
Bonjour Dimitri 👋.

C'est très embêtant en effet ! Avez-vous la possibilité de brancher votre iPhone à une console sous macOS ? Si c'est le cas, il faudrait limiter les logs en le filtre subsystem:io.olvid et nous envoyer le résultat à feedback@olvid.io. C'est possible pour vous ?

Merci beaucoup !

**Comment by dleurs** [comment]
Finalement, j'ai pu récupéré une sauvegarde via iCloud et récupérer le vieux mot de passe de clé associé :) 

J'ai tous mes contacts et conversations

Merci quand même !
