### ISSUE TITLE
Problèmes d'interface v1.1 (705)

### ISSUE THREAD

**Issue by neorelish** [olvid-io/olvid-ios#4]
Bonjour.
Deux problème d'interface décelés :
![IMG_8905](https://github.com/olvid-io/olvid-ios/assets/102987271/669f0c3e-56d7-41c3-8679-2d729de435a2)

https://github.com/olvid-io/olvid-ios/assets/102987271/6ddb9cc2-a8a0-48a5-b0f3-a0602218cd37

Le second efface toute les frappes, impossible de changer l'alias.

**Comment by tbaigner** [comment]
Bonjour 👋
Merci pour vos deux retours. Le premier problème devrait être réglé dans la v1.2 d'Olvid (pour toutes les plateformes d'Apple). Le second est malheureusement toujours présent. Nous allons essayer de le corriger dans la version 1.3. Je n'ai malheureusement pas de « workaround » à vous proposer dans l'immédiat.
Merci beaucoup de nous avoir remonté ces bugs !
Très bonne continuation à vous

**Comment by tbaigner** [comment]
Re-bonjour @neorelish !
Finalement, auriez-vous la gentillesse de tester à nouveau avec la version 1.2 d'Olvid afin de voir si le bug d'effacement des frappes est toujours présent ?
Merci !

**Comment by neorelish** [comment]
Je confirme qu'en 2.1 il n'y est plus. Merci.
